# Site settings
title: 02561 - Computer Graphics
email: s103472@student.dtu.dk
description: > # this means to ignore newlines until "baseurl:"
  Exercises for 02561 - Computer Graphics.

# Build settings
markdown: kramdown
