# Site settings
title: 02561 - Computer Graphics
email: s103472@student.dtu.dk
description: > # this means to ignore newlines until "baseurl:"
  Exercises for 02561 - Computer Graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jokklan.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: none

# Build settings
markdown: kramdown
