# Site settings
title: Computer Graphics
email: s103472@student.dtu.dk
description: > # this means to ignore newlines until "baseurl:"
  Exercises for 02561 - Computer Graphics.
baseurl: "/computer-graphics" # the subpath of your site, e.g. /blog/
url: "http://jokklan.github.io" # the base hostname & protocol for your site
twitter_username: jokklan
github_username:  jokklan
permalink: none

# Build settings
markdown: kramdown
